{% set name = "allagash" %}
{% set version = "0.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/Allagash-{{ version }}.tar.gz
  sha256: 065b9b845180db59c03a72ff6f381361378e30907502c01191474e43116c2648

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pandas >=0.23.0
    - pulp >=1.6.1
    - python >={{ python_min }}
  run_constrained:
    - geopandas >=0.4.1
    - arcgis >=1.8.2

test:
  imports:
    - allagash
    - allagash.coverage
    - allagash.problem
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/apulverizer/allagash
  summary: A Python spatial optimization library
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://apulverizer.github.io/allagash
  dev_url: https://github.com/apulverizer/allagash

extra:
  recipe-maintainers:
    - apulverizer
